create table public."Fello_Customer_Churn_Status" (
  uuid uuid not null default gen_random_uuid (),
  record_id_contact bigint null,
  first_name text null,
  last_name text null,
  email text null,
  phone_number text null,
  contact_owner text null,
  contact_last_activity timestamp without time zone null,
  lead_status text null,
  marketing_contact_status text null,
  contact_create_date timestamp without time zone null,
  record_id_company bigint null,
  company_name text null,
  company_owner text null,
  company_create_date timestamp without time zone null,
  company_phone_number text null,
  company_last_activity timestamp without time zone null,
  city text null,
  country_region text null,
  industry text null,
  added_to_list_on timestamp without time zone null,
  constraint fello_customer_churn_status_pkey primary key (uuid)
) TABLESPACE pg_default;