create table public.mad_dashboard (
  id serial not null,
  total_count bigint null,
  tier1_count bigint null,
  tier1_percentage numeric(6, 2) null,
  tier2_count bigint null,
  tier2_percentage numeric(6, 2) null,
  tier3_count bigint null,
  tier3_percentage numeric(6, 2) null,
  individual_icp_positive bigint null,
  individual_icp_neutral bigint null,
  individual_icp_negative bigint null,
  created_at timestamp with time zone null default now(),
  tier4_count bigint null,
  tier4_percentage numeric null,
  "Not_Enriched_yet" bigint null,
  icp_unclassified text null,
  total_teams integer null,
  total_agents_in_teams integer null,
  "Individual" text null,
  "Small" text null,
  "Medium" text null,
  "Large" text null,
  "Mega" text null,
  "Market_Center" text null,
  "KW" bigint null,
  "Remax" bigint null,
  "BHHS" bigint null,
  "exp_Realty" bigint null,
  constraint mad_dashboard_pkey primary key (id)
) TABLESPACE pg_default;