create table public.only_agents_4 (
  id uuid not null default gen_random_uuid (),
  list_name text null,
  list_company text null,
  list_location text null,
  full_name_zw text null,
  agent_designation_zw text null,
  team_name_zw text null,
  about_agent_zw text null,
  agent_address_zw text null,
  address_url_zw text null,
  agent_email_zw text null,
  personal_email text null,
  agent_phone_numbers_zw text null,
  zillow_profile_url_zw text null,
  sales_last_12_months_zw smallint null,
  total_sales_zw integer null,
  average_price_zw integer null,
  price_range_zw text null,
  website_zw text null,
  linkedin_url_zw text null,
  facebook_url_zw text null,
  instagram_url_zw text null,
  twitter_url_zw text null,
  youtube_url_zw text null,
  tiktok_url_zw text null,
  other_socials_zw text null,
  brokerage_name text null,
  transaction_zipcodes text null,
  license_id text null,
  industry text null,
  fello_customer_status text null,
  date_of_churn date null,
  is_marketing_contact boolean null,
  created_at timestamp with time zone null,
  updated_at timestamp with time zone null,
  team_id uuid null,
  rank smallint null,
  constraint only_agents_4_pkey primary key (id)
) TABLESPACE pg_default;