create table public."Team_Summary" (
  uuid uuid not null default gen_random_uuid (),
  team_name text null,
  "⚠️team_id_⚠️(DONT_USE_THIS!!!)" text null,
  team_size_count integer null,
  brokerage_old text null,
  state text null,
  city text null,
  zip_code text null,
  source text null,
  size text null,
  rank_2025 smallint null,
  volume text null,
  sides real null,
  "Website" text null,
  fello_customer_status text null,
  rt_verified_team_main text[] null,
  team_crm_main text[] null,
  entity text null,
  uuid_text text null,
  serper_results jsonb null,
  ai_website text null,
  reasoning text null,
  website_url_logo_dev text null,
  marketing_tools text[] null,
  brokerage text null,
  constraint team_summary_pkey primary key (uuid)
) TABLESPACE pg_default;

